config/routes.rb
Rails.application.routes.draw do
  resources :apps, only: [:index, :show, :new, :create]
  get 'users/show'
  resources :followings, only: [:create, :destroy]
  devise_for :users
  resources :users, only: [:show]
  root "opinions#new"
  resources :opinions, only: [:new, :create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/app.rb
class App < ApplicationRecord
  validates_presence_of :name
  validates_presence_of :url
  validates_presence_of :description

  has_many :opinions

  def positive
    totalopinions = opinions.count.to_f
    return 0 if totalopinions.zero?

    # rubocop:disable Style/FormatStringToken
    format('%.2f', (100 * opinions.where(sentiment: true).count.to_f / totalopinions))
    # rubocop:enable Style/FormatStringToken
  end

  def negative
    totalopinions = opinions.count.to_f
    return 0 if totalopinions.zero?

    # rubocop:disable Style/FormatStringToken
    format('%.2f', (100 * opinions.where(sentiment: false).count.to_f / totalopinions))
    # rubocop:enable Style/FormatStringToken
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following.rb
class Following < ApplicationRecord
  include ActiveModel::Validations

  validates :followedid, uniqueness: { scope: :followerid }
  validates :followedid, presence: true
  validates :followedid, presence: true
  validates_with FollowingValidation

  belongs_to :followed_user, foreign_key: :followedid, class_name: :User
  belongs_to :follower_user, foreign_key: :followerid, class_name: :User
end

app/models/opinion.rb
class Opinion < ApplicationRecord
  belongs_to :author, foreign_key: 'authorid', class_name: 'User'
  belongs_to :app, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :username
  validates_uniqueness_of :username

  validates_presence_of :fullname

  has_many :opinions, foreign_key: 'authorid', class_name: 'Opinion'

  has_many :followers, foreign_key: :followedid, class_name: :Following
  has_many :follower_users, through: :followers

  has_many :followeds, foreign_key: :followerid, class_name: :Following
  has_many :followed_users, through: :followeds

  has_one_attached :photo
  has_one_attached :coverimage

  def whotofollows
    User.where("id NOT IN (#{(followed_users.pluck('id') << id).join(', ')})")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?
  # before_action :masquerade_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[username fullname])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username fullname photo coverimage])
  end
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  before_action :set_app, only: %i[show edit update destroy]

  # GET /apps
  # GET /apps.json
  def index
    @apps = App.includes(:opinions).all
  end

  # GET /apps/1
  # GET /apps/1.json
  def show; end

  # GET /apps/new
  def new
    @app = App.new
  end

  # POST /apps
  # POST /apps.json
  def create
    @app = App.new(app_params)

    respond_to do |format|
      if @app.save
        format.html { redirect_to root_path, notice: 'App was successfully created.' }
        format.json { render :show, status: :created, location: @app }
      else
        format.html { render :new }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_app
    @app = App.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def app_params
    params.require(:app).permit(:name, :url, :description)
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  before_action :set_following, only: %i[show edit update destroy]

  def create
    @following = Following.new(following_params)

    respond_to do |format|
      if @following.save
        format.html { redirect_to user_path(@following.followed_user), notice: 'Following was successfully created.' }
        format.json { render :show, status: :created, location: @following }
      else
        format.html { render :new }
        format.json { render json: @following.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /followings/1
  # DELETE /followings/1.json
  def destroy
    unfollowed = @following.followed_user
    @following.destroy
    respond_to do |format|
      format.html { redirect_to user_path(unfollowed), notice: 'Following was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_following
    @following = Following.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def following_params
    params.require(:following).permit(:followerid, :followedid)
  end
end

app/controllers/opinions_controller.rb
class OpinionsController < ApplicationController
  before_action :set_opinion, only: %i[show edit update destroy]

  # GET /opinions/new
  def new
    @opinion = Opinion.new(authorid: current_user.id)
    @opinions = Opinion.order(created_at: :desc).includes(:author).includes(:app).all
    @apps = App.all
    @whotofollow = current_user.whotofollows
    @whoifollow = current_user.followed_users
  end

  # POST /opinions
  # POST /opinions.json
  def create
    @opinion = Opinion.new(opinion_params)

    respond_to do |format|
      if @opinion.save
        format.html { redirect_to root_path, notice: 'Opinion was successfully created.' }
        format.json { render :show, status: :created, location: @opinion }
      else
        format.html { render :new }
        format.json { render json: @opinion.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_opinion
    @opinion = Opinion.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def opinion_params
    params.require(:opinion).permit(:text, :authorid, :app_id, :sentiment)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users/1
  # GET /users/1.json
  def show
    @opinions = @user.opinions.includes(:author)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.fetch(:user, {})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def user_avatar(user, size = 40)
    if user.photo.attached?
      user.photo.variant(resize: "#{size}x#{size}!")
    else
      gravatar_image_url(user.email, size: size)
    end
  end

  def user_cover(user)
    if user.coverimage.attached?
      user.coverimage.variant(resize: '600x200!')
    else
      'default_cover.jpg'
    end
  end
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/following_validation.rb
class FollowingValidation < ActiveModel::Validator
  def validate(record)
    record.errors[:name] << "You can't invite yourself" if record.followedid == record.followerid
  end
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/opinions_helper.rb
module OpinionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/apps/_form.html.erb
<%= form_with(model: app, local: true) do |form| %>
  <% if app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
        <% app.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name, class: "text-secondary text-uppercase"  %>
    <%= form.text_field :name, class: "form-control"  %>
  </div>

  <div class="field form-group">
    <%= form.label :url, class: "text-secondary text-uppercase"  %> (without http://)
    <%= form.text_field :url, class: "form-control"  %>
  </div>

  <div class="field form-group">
    <%= form.label :description, class: "text-secondary text-uppercase"  %>
    <%= form.text_area :description, class: "form-control"  %>
  </div>

  <div class="actions">
    <%= form.submit "Add new app", class: "btn btn-primary"  %>
  </div>
<% end %>

app/views/apps/index.html.erb
    <div class="col-8 overflow-auto p-0">

      <main class="position-absolute w-100 p-5">
        <div class="container">
          <div class="row">
            <div class="col-12 bg-white border rounded">
              <div class="p-3">
                <h5 class="text-uppercase font-weight-bold text-secondary">Apps</h5>

                <% @apps.each do |app| %>


                  <div class="container-fluid p-0">
                    <div class="row pb-5">
                      <div class="col-12 pl-4">
                        <div class="row">
                          <div class="col-12"><%= link_to app.name, app %></div>
                        </div>
                        <div class="row">
                          <div class="col-12"><%= link_to app.url, "http://#{app.url}" %></div>
                        </div>
                        <div class="row">
                          <div class="col-12">Positive: <%= app.positive %> %</div>
                        </div>
                        <div class="row">
                          <div class="col-12">Negative: <%= app.negative %> %</div>
                        </div>
                      </div>
                    </div>
                  </div>

                <% end %>

              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
    <div class="col-4 overflow-auto p-0">
      <aside class="position-absolute w-100 p-3">
      </aside>
    </div>

app/views/apps/new.html.erb
    <div class="col-8 overflow-auto p-0">
      <main class="position-absolute w-100 p-5">
        <h1>New App</h1>

        <%= render 'form', app: @app %>

      </main>
    </div>
    <div class="col-4 overflow-auto p-0">
      <aside class="position-absolute w-100 p-5">
      </aside>
    </div>

app/views/apps/show.html.erb
    <div class="col-8 overflow-auto p-0">

      <main class="position-absolute w-100 p-5">
        <div class="container">
          <div class="row">
            <div class="col-12 bg-white border rounded">
              <div class="p-3">
                <h5 class="text-uppercase font-weight-bold text-secondary">Opinions about <%= @app.name %></h5>

                <% @app.opinions.each do |opinion| %>


                  <div class="container-fluid p-0">
                    <div class="row pb-5">
                      <div class="col-1">
                        <%= image_tag user_avatar(opinion.author, 50) %>
                      </div>
                      <div class="col-11 pl-4">
                        <div class="row">
                          <div class="col-12"><%= link_to opinion.author.username, opinion.author %> <% if opinion.app %> rated <%= link_to opinion.app.name, opinion.app %><% end %></div>
                        </div>
                        <div class="row">
                          <div class="col-12">Opinion: <%= opinion.sentiment ? "Positive" : "Negative" %></div>
                        </div>
                        <div class="row">
                          <div class="col-12"><%= opinion.text %></div>
                        </div>
                      </div>
                    </div>
                  </div>

                <% end %>

              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
    <div class="col-4 overflow-auto p-0">
    
      <aside class="position-absolute w-100 p-3">
        <h5 class="text-uppercase font-weight-bold text-secondary"><%= @app.name %></h5>
        <div class="container-fluid pb-4">
          <div class="row">
            <div class="col-6 flex-column justify-content-center text-center p-2">
            <div class="text-uppercase font-weight-bold text-secondary">Positive</div><div class="text-success"><%= @app.positive %> %</div>
            </div>
            <div class="col-6 flex-column justify-content-center text-center p-2">
            <div class="text-uppercase font-weight-bold text-secondary">Negatve</div><div class="text-danger"><%= @app.negative %> %</div>
            </div>
          </div>
        </div>

      </aside>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppCritic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

  <div class="container-fluid bg-1 d-flex h-100 flex-column">
    <div class="row bg-2 flex-fill d-flex justify-content-start">
      <div class="col-2 bg-left-aside">
        <aside>
          <% if current_user %>
            <div class="d-flex justify-content-center text-center p-3"><%= image_tag user_avatar(current_user, 100), class: "rounded-circle" %></div>
            <div class="d-flex justify-content-center text-center pb-4 text-light"><%= current_user.fullname %></div>
            <div class="d-flex justify-content-center text-center pb-4"><%= link_to current_user.username, root_path %></div>
            <div class="d-flex justify-content-center">
            <ul class="nav navbar-custom flex-column">
              <li class="nav-item"> <%= link_to apps_path, class: "nav-link text-muted h6" do %> <i class="fas fa-star-half-alt"></i> APP REVIEWS <% end %> </li>
              <li class="nav-item"> <%= link_to root_path, class: "nav-link text-muted h6" do %> <i class="fas fa-edit"></i> RATE AN APP <% end %></li>
              <li class="nav-item"> <%= link_to new_app_path, class: "nav-link text-muted h6" do %> <i class="fas fa-folder-plus"></i> ADD AN APP <% end %> </li>
            </ul>
            </div>
          <% end %>
        </aside>
      </div>
      <div class="col-10 bg-1 d-flex h-100 flex-column">
        <div class="row bg-5">
          <div class="col-12 bg-nav">
            <nav class="navbar navbar-expand">
              <%= link_to root_path, class: "navbar-brand text-light" do %> <i class="fas fa-user-edit"></i> AppCritic <% end %>

              <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <span class="nav-link"><%= notice %></span>
                </li>
                <li class="nav-item">
                  <span class="nav-link"><%= alert %></span>
                </li>
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to edit_user_registration_path, class: "nav-link text-light h6" do %><i class="far fa-id-card"></i> Settings <% end %>
                </li>
                <li class="nav-item">
                  <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light h6" do %> <i class="fas fa-sign-out-alt"></i> Log Out <% end %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to new_user_session_path, class: "nav-link text-light h6" do %> <i class="fas fa-sign-in-alt"></i> Log In <% end %>
                </li>
                <li>
                <%= link_to new_registration_path(resource_name), class: "nav-link text-light h6" do %> <i class="fas fa-user-plus"></i> New account <% end %>
                </li>
              <% end %>
              </ul>
              
              
            </nav>
          </div>
        </div>
        <div class="row bg-6 flex-fill d-flex justify-content-start bg-main">
          <%= yield %>
        </div>
      </div>
    </div>
  </div>
  </body>
</html>

app/views/opinions/_form.html.erb
<%= form_with(model: opinion, local: true) do |form| %>
  <% if opinion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(opinion.errors.count, "error") %> prohibited this opinion from being saved:</h2>

      <ul>
        <% opinion.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :app_id, class: "text-secondary text-uppercase" %>
    <%= form.select :app_id, @apps.collect { |app| [app.name, app.id] }, {}, {class: "form-control"} %>
  </div>

  <div class="field">
    <div class="form-check">
    <%= form.radio_button :sentiment, true, class: "form-check-input" %>
    <%= form.label :sentiment_true, "Positive", class: "form-check-label text-secondary text-uppercase" %>
    </div>
    <div class="form-check">
    <%= form.radio_button :sentiment, false, class: "form-check-input" %>
    <%= form.label :sentiment_false, "Negative", class: "form-check-label text-secondary text-uppercase" %>
    </div>
  </div>

  <div class="field form-group">
    <%= form.label :opinion, class: "control-label text-secondary text-uppercase" %>
    <%= form.text_area :text, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.hidden_field :authorid %>
  </div>

  <div class="actions">
    <%= form.submit "SUBMIT", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/opinions/_rating_form.html.erb
<%= form_with(model: opinion, local: true) do |form| %>
  <% if opinion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(opinion.errors.count, "error") %> prohibited this opinion from being saved:</h2>

      <ul>
        <% opinion.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="field">
    <%= form.label :authorid %>
    <%= form.text_field :authorid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/opinions/new.html.erb
    <div class="col-8 overflow-auto p-0">
      <%= image_tag user_cover(current_user), size: "600x200", class: "cover-image" %>

      <main class="position-absolute w-100 p-5">

        <div class="container">
          <div class="row pb-5">
            <div class="col-12 bg-white border rounded">
              <div class="p-3">
              <h5 class="text-uppercase font-weight-bold text-secondary">Review an app</h5>
              <%= render 'form', opinion: @opinion %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-12 bg-white border rounded">
              <div class="p-3">
                <h5 class="text-uppercase font-weight-bold text-secondary">App ratings</h5>
                <% @opinions.each do |opinion| %>
                  <div class="container-fluid p-0">
                    <div class="row pb-5">
                      <div class="col-1">
                        <%= image_tag user_avatar(opinion.author, 50) %>
                      </div>
                      <div class="col-11 pl-4">
                        <div class="row">
                          <div class="col-12"><%= link_to opinion.author.username, opinion.author %> <% if opinion.app %> rated <%= link_to opinion.app.name, opinion.app %><% end %></div>
                        </div>
                        <div class="row">
                          <div class="col-12">Opinion: <%= opinion.sentiment ? "Positive" : "Negative" %></div>
                        </div>
                        <div class="row">
                          <div class="col-12"><%= opinion.text %></div>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
    <div class="col-4 overflow-auto p-0">
      <aside class="position-absolute w-100 p-5">
        <h5 class="text-uppercase font-weight-bold text-secondary">Who to follow</h5>
        <ul>
        <% @whotofollow.each do |user| %>
          <div class="d-flex align-items-center pb-3">
          <%= image_tag user_avatar(user, 50), class: "rounded-circle" %>
          <span class="pl-3"><%= link_to user.username, user %><br><%= user.fullname %></span>
          </div>
        <% end %>
        </ul>
        <h5 class="text-uppercase font-weight-bold text-secondary">People you follow</h5>
        <ul>
        <% @whoifollow.each do |user| %>
          <div class="d-flex align-items-center pb-3">
          <%= image_tag user_avatar(user, 50), class: "rounded-circle" %>
          <span class="pl-3"><%= link_to user.username, user %><br><%= user.fullname %></span>
          </div>
        <% end %>
        </ul>
      </aside>
    </div>

app/views/opinions/rate.html.erb
    <div class="col-8 bg-2 overflow-auto p-0">
      <main class="bg-1 position-absolute w-100 p-5">

        <%= image_tag user_cover(current_user), size: "600x200" %>

        <h1> Write a review </h1>
        <%= render 'rating_form', opinion: @opinion %>

      </main>
    </div>
    <div class="col-4 bg-4 overflow-auto p-0">
      <aside class="bg-2 position-absolute w-100 p-5">

      </aside>
    </div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/show.html.erb
    <div class="col-8 overflow-auto p-0">
      <%= image_tag user_cover(@user), size: "600x200", class: "cover-image" %>

      <main class="position-absolute w-100 p-5">
        <div class="container">
          <div class="row">
            <div class="col-12 bg-white border rounded">
              <div class="p-3">
                <h5 class="text-uppercase font-weight-bold text-secondary">App ratings</h5>
                <% @opinions.each do |opinion| %>
                  <div class="container-fluid p-0">
                    <div class="row pb-5">
                      <div class="col-1">
                        <%= image_tag user_avatar(opinion.author, 50) %>
                      </div>
                      <div class="col-11 pl-4">
                        <div class="row">
                          <div class="col-12"><%= link_to opinion.author.username, opinion.author %> <% if opinion.app %> rated <%= link_to opinion.app.name, opinion.app %><% end %></div>
                        </div>
                        <div class="row">
                          <div class="col-12">Opinion: <%= opinion.sentiment ? "Positive" : "Negative" %></div>
                        </div>
                        <div class="row">
                          <div class="col-12"><%= opinion.text %></div>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
    <div class="col-4 overflow-auto p-0">
      <aside class="position-absolute w-100 p-3">
        <div class="d-flex align-items-center">
        <%= image_tag user_avatar(@user, 80), class: "rounded-circle" %>
        <span class="pl-3"><%= @user.fullname %></span>
        </div>

        <% unless @user.username == current_user.username %>
        <div class="d-flex justify-content-center text-center pb-4 pt-4">
          <% if @user.follower_users.where(id: current_user.id).count > 0 %>
            <%= link_to "Unfollow #{@user.username}", Following.find_by(followerid: current_user.id, followedid: @user.id), method: :delete, class: "btn btn-primary btn-sm text-white" %>
          <% else %>
            <%= link_to "Follow #{@user.username}", followings_path(following: {followerid: current_user.id, followedid: @user.id }), method: :post, class: "btn btn-primary btn-sm text-white" %>
          <% end %>
        </div>
        <% end %>

        <div class="container-fluid pb-4">
          <div class="row">
            <div class="col-4 flex-column justify-content-center text-center p-2">
            <div class="text-uppercase font-weight-bold text-secondary">Opinions</div><%= @user.opinions.count %>
            </div>
            <div class="col-4 flex-column justify-content-center text-center p-2">
            <div class="text-uppercase font-weight-bold text-secondary">Followers</div><%= @user.follower_users.count %>
            </div>
            <div class="col-4 flex-column justify-content-center text-center p-2">
            <div class="text-uppercase font-weight-bold text-secondary">Following</div><%= @user.followed_users.count %>
            </div>
          </div>
        </div>

        <h5 class="text-uppercase font-weight-bold text-secondary">Followed by</h5>

        <% @user.follower_users.each do |user| %>
          <div class="d-flex align-items-center pb-3">
          <%= image_tag user_avatar(user, 50), class: "rounded-circle" %>
          <span class="pl-3"><%= link_to user.username, user %><br><%= user.fullname %></span>
          </div>
        <% end %>

      </aside>
    </div>